[postgresql_prod_admin]
user="postgres.vqgqlwvrovzgvputyokg" 
password="6NEIhhdg5ZAvkcM7"
host="aws-0-us-west-1.pooler.supabase.com"
port=6543
dbname="postgres"


[postgresql_prod_readonly]
user="readonly_user.vqgqlwvrovzgvputyokg" 
password="5NEIhhhdgg4zAvkcM2"
host="aws-0-us-west-1.pooler.supabase.com"
port=6543
dbname="postgres"